owncloud:
  image: owncloud
  labels:
    io.rancher.glb: 'true'
  links:
    - db

db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=password

owncloud-lb:
  image: rancher/none
  labels:
    io.rancher.glb: 'true'
    io.rancher.glb.http: 'true'
    io.rancher.container.agent.role: environmentAdmin
    io.rancher.container.create_agent: 'true'
