version: '2'

services:

gitlab-server:
  labels:
    io.rancher.sidekicks: gitlab-data
    io.rancher.glb: 'true'
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:latest
  volumes_from:
  - gitlab-data
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:latest
  volumes:
  - /etc/gitlab
  - /var/log/gitlab
  - /var/opt/gitlab

gitlab-server-lb-http:
  image: rancher/none
  labels:
    io.rancher.glb: 'true'
    io.rancher.container.agent.role: environmentAdmin
    io.rancher.glb.http: 'true'
    io.rancher.container.create_agent: 'true'
