.catalog:
  name: Gitlab Community
  version: latest
  description: |
    Gitlab CE is a free GitHub alternative
  minimum_rancher_version: v0.56.0
  maintainer: "Alexis Ducastel <alexis@ducastel.net>"
  uuid: gitlab-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "git.example.com"
      type: "string"
    - variable: "gitlab_omnipus_prefix"
      label: "Gitlab external_url prefix:"
      description: |
        This is needed for the docker-compose file to set the correct external_url
      default: 'https://'
      required: true
      type: "string"
      options:
        - 'https://'
        - 'http://'
      questions:
        - variable: "http_fqdn"
          label: "LB FQDN for HTTP access"
          description: "App name for FQDN by HTTP"
          type: "string"
          required: true
          default: "gitlab-server-http"
        - variable: "https_fqdn"
          label: "LB FQDN for HTTPS access"
          description: "App name for FQDN by HTTPS"
          type: "string"
          required: true
          default: "gitlab-server-http"

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

gitlab-data:
  scale: 1
  retain_ip: true

gitlab-server-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${http_fqdn}
        priority: 1
        protocol: http
        service: gitlab-server
        source_port: 8082
        target_port: 80
      - hostname: ${https_fqdn}
        priority: 1
        protocol: http
        service: gitlab-server
        source_port: 8082
        target_port: 443
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
