version: '2'

services:
  game2048:
    image: alexwhen/docker-2048
    labels:
      io.rancher.glb: 'true'
  game2048-lb:
    image: rancher/none
    labels:
      io.rancher.glb: 'true'
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.glb.http: 'true'
      io.rancher.container.create_agent: 'true'
