version: '2'

services:
  dokuwiki-server:
    labels:
      io.rancher.sidekicks: dokuwiki-data
      io.rancher.glb: 'true'
    hostname: ${dokuwiki_hostname}
    image: ununseptium/dokuwiki-docker
    volumes_from:
      - dokuwiki-data
   
  dokuwiki-data:
    labels:
      io.rancher.container.start_once: 'true'
    entrypoint:
      - /bin/true
    hostname: dokuwikidata
    image: ununseptium/dokuwiki-docker
    volumes:
      - /var/www/html/data
      - /var/www/html/lib/plugins

  dokuwiki-server-lb:
    image: rancher/none
    labels:
      io.rancher.glb: 'true'
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.glb.http: 'true'
      io.rancher.container.create_agent: 'true'
