.catalog:
  name: Dokuwiki
  version: 2016-06-26a
  description: |
    DokuWiki is a simple to use and highly versatile Open Source wiki software that doesn't require a database.
  minimum_rancher_version: v0.56.0
  maintainer: "Tim Kopplow <tim@arctium.io>"
  uuid: dokuwiki-0
  questions:
  - variable: "fqdn"
    label: "LB FQDN"
    description: "App name for FQDN"
    type: "string"
    required: true
    default: "dokuwiki"


dokuwiki-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

dokuwiki-data:
  scale: 1
  retain_ip: true

dokuwiki-server-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${fqdn}
        priority: 1
        protocol: http
        service: dokuwiki-server
        source_port: 8082
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
