version: '2'

services:
  jenkins-primary:
    image: "jenkins:1.642.2"
    labels:
      io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
      io.rancher.container.hostname_override: container_name
      io.rancher.glb: 'true'
    volumes_from:
      - jenkins-plugins
      - jenkins-datavolume
    entrypoint: /usr/share/jenkins/rancher/jenkins.sh
  jenkins-plugins:
    image: rancher/jenkins-plugins:v0.1.1
  jenkins-datavolume:
    image: "busybox"
    volumes:
      - /var/jenkins_home
    labels:
      io.rancher.container.start_once: true
    entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
  jenkins-primary-lb:
    image: rancher/none
    labels:
      io.rancher.glb: 'true'
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.glb.http: 'true'
      io.rancher.container.create_agent: 'true'
