.catalog:
  name: "RocketChat"
  version: "v0.1-educaas"
  description: "Have your own Slack like online chat, built with Meteor."
  uuid: rocketchat-0
  minimum_rancher_version: v0.51.0
  questions:
  - variable: "rocketchatfqdn"
    label: "RocketChat LB FQDN"
    description: "App name for RocketChat FQDN"
    type: "string"
    required: true
    default: "rocketchat"
  - variable: "hubotfqdn"
    label: "Hubot LB FQDN"
    description: "App name for Hubot FQDN"
    type: "string"
    required: true
    default: "hubot"

rocketchat:
rocketchatlb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${rocketchatfqdn}
        priority: 1
        protocol: http
        service: rocketchat
        source_port: 8082
        target_port: 3000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
hubotlb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${hubotfqdn}
        priority: 1
        protocol: http
        service: hubot
        source_port: 8082
        target_port: 8080
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000