version: '2'

services:
  ghost:
    image: ghost
    labels:
      io.rancher.glb: 'true'

  ghost-lb:
    image: rancher/none
    labels:
      io.rancher.glb: 'true'
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.glb.http: 'true'
      io.rancher.container.create_agent: 'true'
