.catalog:
  name: "TeamCity"
  version: "v0.0.1"
  description: "TeamCity Server"
  uuid: teamcity-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "fqdn"
      label: "LB FQDN"
      description: "App name for FQDN"
      type: "string"
      required: true
      default: "teamcity"

    - variable: scale
      description: "Number of TeamCity Agents"
      label: "Number of TeamCity Agents"
      required: true
      default: "1"
      type: "int"
    - variable: postgress_container
      description: "Define a linked postgress container name"
      label: "Postgres Container"
      required: true
      default: "db"
      type: "string"
    - variable: postgress_port
      description: "Port for Postgres"
      label: "Postgres Port"
      required: true
      default: "5432"
      type: "int"
    - variable: postgres_data
      description: "Postgres Data Folder"
      label: "Postgres Data"
      required: true
      default: "/var/lib/postgresql/data/pgdata"
      type: "string"
    - variable: postgres_db
      description: "Postgres Database"
      label: "Postgres Database"
      required: true
      default: "teamcity"
      type: "string"
    - variable: postgres_user
      description: "Postgres User"
      label: "Postgres User"
      required: true
      default: "teamcity"
      type: "string"
    - variable: postgres_password
      description: "Postgres Password"
      label: "Postgres Password"
      required: true
      default: "teamcity"
      type: "string"
    - variable: http_proxy
      description: "In case you are at corporate network, setup http_proxy variable if needed"
      label: "http_proxy"
      required: false
      default: ""
      type: "string"
    - variable: https_proxy
      description: "In case you are at corporate network, setup https_proxy variable if needed"
      label: "https_proxy"
      required: false
      default: ""
      type: "string"
    
teamcity-agent:
  scale: ${scale}
  retain_ip: true

teamcity-server-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${fqdn}
        priority: 1
        protocol: http
        service: teamcity-server
        source_port: 8082
        target_port: 8111
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
