.catalog:
  name: "SonarQube"
  version: "v0.0.1"
  description: "SonarQube"
  uuid: sonarqube-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: "fqdn"
      label: "LB FQDN"
      description: "App name for FQDN"
      type: "string"
      required: true
      default: "sonarqube"
    - variable: postgress_port
      description: "Port for Postgres"
      label: "Postgres Port"
      required: true
      default: "5432"
      type: "int"
    - variable: postgres_data
      description: "Postgres Data Folder"
      label: "Postgres Data"
      required: true
      default: "/var/lib/postgresql/data/pgdata"
      type: "string"
    - variable: postgres_db
      description: "Postgres Database"
      label: "Postgres Database"
      required: true
      default: "sonar"
      type: "string"
    - variable: postgres_user
      description: "Postgres User"
      label: "Postgres User"
      required: true
      default: "sonar"
      type: "string"
    - variable: postgres_password
      description: "Postgres Password"
      label: "Postgres Password"
      required: true
      default: "sonar"
      type: "string"
    - variable: http_proxy
      description: "In case you are at corporate network, setup http_proxy variable"
      label: "http_proxy"
      required: false
      default: ""
      type: "string"
    - variable: https_proxy
      description: "In case you are at corporate network, setup https_proxy variable"
      label: "https_proxy"
      required: false
      default: ""
      type: "string"

sonarqube-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${fqdn}
        priority: 1
        protocol: http
        service: sonarqube
        source_port: 8082
        target_port: 9000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
