.catalog:
  name: "Nuxeo Platform"
  version: 8.1-rancher1
  description: |
    Enterprise Content Management 
    Platform for Business Applications
  uuid: nuxeo-1
  questions:
    - variable: clid
      description: "A valid CLID to be able to download packages from Nuxeo Online Services. in the form part1\npart2"
      label: "CLID"
      type: "string"
      required: false
      default: ""
    - variable: "packages"
      type: "string"
      label: "List of Nuxeo packages"
      description: |
        List of Nuxeo packages 
      default: nuxeo-web-mobile nuxeo-drive nuxeo-diff nuxeo-spreadsheet nuxeo-dam nuxeo-template-rendering nuxeo-template-rendering-samples nuxeo-showcase-content
    - variable: url
      description: "The URL that this nuxeo instance should serve"
      label: "Nuxeo URL"
      type: "string"
      required: true
      default: "http://localhost:8080/"    
    - variable: volumedriver
      type: "string"
      label: "Volume driver"
      description: |
        Specifiy docker volume driver to use
      default: local
    - variable: "fqdn"
      label: "LB FQDN"
      description: "App name for FQDN"
      type: "string"
      required: true
      default: "nuxeo"

nuxeo:
  scale: 1
  health_check:
    port: 8080
    # Interval is measured in milliseconds
    interval: 5000
    unhealthy_threshold: 5
    # For TCP, request_line needs to be ''
    # TCP Example: 
    # request_line: ''
    request_line: GET /nuxeo/login.jsp 
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000

elasticsearch:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "true"

lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${fqdn}
        priority: 1
        protocol: http
        service: nuxeo
        source_port: 8082
        target_port: 8080
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000